import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  children: React.ReactNode;
  first: React.ReactNode;
  second: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen  flex items-center justify-center p-24">
          <Accordion type="single" collapsible className="w-full">
            <AccordionItem value="first-route">
              <AccordionTrigger>First route</AccordionTrigger>
              <AccordionContent>{props.first}</AccordionContent>
            </AccordionItem>
            <AccordionItem value="second-route">
              <AccordionTrigger>Second route</AccordionTrigger>
              <AccordionContent>{props.second}</AccordionContent>
            </AccordionItem>
          </Accordion>
        </div>
        {props.children}
      </body>
    </html>
  );
}
